@extends('Masters.ClientSpace')
@section('css')

<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/1.1.1/css/bootstrap-multiselect.min.css" integrity="sha512-jpey1PaBfFBeEAsKxmkM1Yh7fkH09t/XDVjAgYGrq1s2L9qPD/kKdXC/2I6t2Va8xdd9SanwPYHIAnyBRdPmig==" crossorigin="anonymous" referrerpolicy="no-referrer" />

@section('spacedetail')
<input type="hidden" class='gocoworq_lead_count' value="{{$count[0]->Gocoworq}}"  >
<input type="hidden" class='manual_lead_count' value="{{$count[0]->Manual}}">
<input type="hidden" class='all_lead_count' value="{{(int) $count[0]->Gocoworq + (int) $count[0]->Manual }}">
<input type="hidden" class='pastInvoiceUrl' value="{{route('client.pastEmail')}}">
<input type="hidden" name="" class='custom_mail_id' value="{{app('request')->input('email')}}">
<div class="content-wrapper">
    {{ csrf_field() }}
    <meta name="csrf-token" content="{{ csrf_token() }}">


    <div class="container NotSubScribed">
    @if (\Session::has('success'))
    <div class="alert p-3 text-success">
           {!! \Session::get('success') !!}
    </div>
@endif

@if (\Session::has('danger'))
    <div class="alert p-3 text-danger">
           {!! \Session::get('danger') !!}
    </div>
@endif

<!-- modal for alerts -->
<div class="modal fade" id="modal-custom-alert" style="display: none;" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content animated flipInX">
                    <div class="modal-body">
                          <p class='customConfirmTitle'> </p>
                          <button class="btn btn-info waves-effect waves-light m-1" id='customConfirmOk'  data-dismiss="modal" > yes,continue</button>
                          <a href="javascript:void(0)" data-dismiss="modal" class='text-underline'>Cancel</a>
                    </div>
                </div>
            </div>
</div>


<input type="hidden" name="" class='pastEmailsurl' value="{{url('client/pastEmail')}}">
<div class="modal fade" id="modal-mailMerge" style="display: none;" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content animated flipInX">
               
                    <div class="modal-body">
                          <p class='mail_merge_heading' style='font-weight: 600;'>COPY THE FOLLOWING SNIPPET AND PASTE IT IN YOUR EMAIL WHERE YOU WOULD LIKE THE DATA TO BE INSERTED</p>
                          <div class="input-group mb-3">
<input type="text" name="" class='form-control mail_merge_input' >
                          </div>
                          <button class="btn btn-warning primary-btn waves-effect waves-light m-1" onclick="copyText();" >Copy</button>
                          <button class="btn  waves-effect btn-info waves-light m-1" data-dismiss="modal" > Close</button>
                    </div>
                </div>
            </div>
        </div>

    <div class="card">
        <div class="card-body">
        <div class="card-title">Send Marketing Emails to your Customers/Leads</div>
        <form action="{{url('client/sendEmailToLead')}}" id='sendEmailForm' class='mt-3'  >
     @csrf
     <input type="hidden" name="email_body" class='emailHtmlContent' >
        <div class="selectAudianceDiv">
        <div class="row">
        <div class="col-md-12">
        <label class='mb-1'>Select recipients</label>
        </div>
<div class="column col-md-2  pr-md-0 mr-md-3 ">
    <div class="icheck-material-primary">
        <input checked="" type="radio" id="gleads" name="audiance" value="1">
        <label for="gleads">Gocoworq Leads<i class="fas fa-question-circle" data-toggle="tooltip" data-placement="top" title="All Leads/Inquiries generated by gocoworq.com online listing." style="font-size: 12px;" aria-hidden="true"></i></label>
    </div>
</div>
<div class="column col-md-2 pl-md-0">
    <div class="icheck-material-primary">
        <input type="radio" id="mleads" name="audiance" value="2">
        <label for="mleads">Manual Leads <i class="fas fa-question-circle" data-toggle="tooltip" data-placement="top" title="All Leads/Inquiries you entered manually for this space." style="font-size: 12px;" aria-hidden="true"></i></label>
    </div>  
</div>
<div class="column col-md-2 pl-md-0">
    <div class="icheck-material-primary">
        <input type="radio" id="aleads" name="audiance" value="3">
        <label for="aleads">All Leads<i class="fas fa-question-circle ml-1" data-toggle="tooltip" data-placement="top" title="All gocoworq and manual leads." style="font-size: 12px;" aria-hidden="true"></i></label>
    </div>  
</div>
<div class="column col-md-2 pl-md-0">
    <div class="icheck-material-primary">
    
   

   
   <input type="radio" id="cleads" {{ app('request')->input('email') ? 'checked' : '' }} name="audiance" value="4">
        <label for="cleads">Custom Leads<i class="fas fa-question-circle ml-1"  data-toggle="tooltip" data-placement="top" title="You can select customized recipients from all leads." style="font-size: 12px;" aria-hidden="true"></i></label>
    </div>  
</div>

</div>
</div>
<div class="row mt-3 multiselectParentDiv {{ app('request')->input('email') ? '' : 'd-none' }} ">
<div class="col-md-3 mb-2">
<select id="custom-email-multiselect" name='custom_email_ids[]' multiple="multiple">
@foreach($space->inquiries->where('id_hide' , 0) as  $inquiry)
 <option value="{{$inquiry->id}}">{{$inquiry->email}}</option>
@endforeach
</select>
</div>

</div>

<div class="emailDesignDiv ">
<div class="row mt-2">
<div class="col-md-12 ">
                                    <label for="input-4">Subject</label>
                                    <input required type="text" class="form-control" id="subject" name="subject" placeholder="Email Subject">
                                </div>
                          
                             
                      
</div>

<div class=" mt-3">
                                <label for="input-4">Email Body</label>
                                </div>

<div id="summernote"></div>

<div class="row mt-3">
<div class="col-md-3 mt-2 mt-md-0">
                       <label for="full_name">From Name</label>
                                    <input required type="text" class="form-control" id="full_name" name="full_name" placeholder="{{Auth::user()->full_name}}"> 
                       </div> 
<div class="col-md-3 mt-2 mt-md-0">
<div class="form-group">
  <label for=""> Mail Merge Fields <i class="fas fa-question-circle c-pointer ml-1" data-toggle="tooltip" data-placement="top" title="Use merge fields for replacing recipients' information like First Name and Last Name. Select the field from dropdown menu here and we will give you exact text to put in your email body." style="font-size: 12px;" aria-hidden="true"></i></label>

                                    <select id="mail_merge_field" class="form-control">
                                                <option value="0">Mail Merge Fields</option>
                                                <option value="Full Name">Full Name</option>
                                                <option value="Phone Number">Phone Number</option>
                                                <option value="Email">Email</option>
                                    </select>
                                    </div>
                           </div>
                         
                           
    
</div>
<div class="row align-items-center">
<div class="col-md-3">
                           <div class="icheck-material-info">
                                            <input type="checkbox" id="Schedule" name="Schedule"  onclick="openDatePicker(this);">
                                            <label for="Schedule" style="font-weight: 500;">Schedule for later?</label>
                                        </div>
                           </div>
                           <div class="scheduleDateDiv d-none col-md-3">
                           <input class="date form-control" name='scheduleDate'  min="{{date('Y-m-d')}}T{{date('h:m')}}"  type="datetime-local">
                           </div>
</div>

<button type="submit" class="btn btn-info float-right  waves-effect waves-light m-1 mt-3">Send Email</button>
<a href="{{url('client/pastEmail')}}" class='pull-right  mt-4 mr-2' style='text-decoration: underline;'> Cancel</a>
</div>

        </form>  
        </div>
    </div>

    </div>
    <!-- End container-fluid-->

</div><!--End content-wrapper-->

@endsection

@section('script')
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-multiselect/1.1.1/js/bootstrap-multiselect.min.js" integrity="sha512-fp+kGodOXYBIPyIXInWgdH2vTMiOfbLC9YqwEHslkUxc8JLI7eBL2UQ8/HbB5YehvynU3gA3klc84rAQcTQvXA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>



<script src="{{asset('js/client/sendMail.js')}}"></script>
@endsection